
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ChkTranslator:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: python3.8
      Policies: 
        - Statement:
          - Sid: chkstatement
            Effect: Allow
            Action:
            - sagemaker:*
            - events:*
            - ec2:*
            - cloudwatch:*
            Resource: '*'
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 8 * * ? *)
            Enabled: True 