name: Chuck Norris Translator

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Send Lambda Code to S3        
        run: |
          aws s3api put-object --bucket chuck-norris-translator --key lambda-code/src.zip --region us-west-2 --body ./src.zip

      - name: Create Lambda Function
        run: | 
          aws cloudformation deploy \
            --stack-name chuck-norris-translator \
            --no-fail-on-empty-changeset \
            --template-file ./infra.yml \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Update Lambda Function Code
        run: |
          aws lambda update-function-code --function-name chuck-norris-translator-Function-fNouBu0iur8e --s3-bucket chuck-norris-translator --s3-key lambda-code/src.zip